const WORDS = [
  {
    "sublist": 1,
    "word": "analyse",
    "pos": "verb",
    "definition": "to examine something carefully and in detail",
    "synonyms": ["examine","investigate","study","scrutinise"],
    "antonyms": ["ignore","overlook","neglect"],
    "example_sentence": "Scientists ___ water samples to check for pollution.",
    "word_family": "analysis, analytical, analyst",
    "collocations": "carry out an analysis, analyse data, analyse results",
    "taboo_words": ["examine","study","look at","investigate","research"]
  },
  {
    "sublist": 1,
    "word": "approach",
    "pos": "noun / verb",
    "definition": "a way of dealing with a situation or problem",
    "synonyms": ["method","strategy","technique","way"],
    "antonyms": ["avoidance","neglect"],
    "example_sentence": "The teacher used a creative ___ to explain fractions.",
    "word_family": "approachable, unapproachable",
    "collocations": "adopt an approach, take an approach, practical approach",
    "taboo_words": ["method","strategy","way","technique","deal with"]
  },
  {
    "sublist": 1,
    "word": "area",
    "pos": "noun",
    "definition": "a subject or field of activity",
    "synonyms": ["field","domain","subject","discipline"],
    "antonyms": ["whole","entirety"],
    "example_sentence": "Medicine is an ___ that requires years of study.",
    "word_family": "areal",
    "collocations": "subject area, area of research, area of expertise",
    "taboo_words": ["field","subject","domain","topic","discipline"]
  },
  {
    "sublist": 1,
    "word": "assess",
    "pos": "verb",
    "definition": "to evaluate or judge the quality of something",
    "synonyms": ["evaluate","judge","measure","appraise"],
    "antonyms": ["ignore","neglect","overlook"],
    "example_sentence": "Doctors ___ patients before deciding on treatment.",
    "word_family": "assessment, assessor, reassess",
    "collocations": "assess the situation, assess the risk, assess the impact",
    "taboo_words": ["evaluate","judge","measure","examine","appraise"]
  },
  {
    "sublist": 1,
    "word": "assume",
    "pos": "verb",
    "definition": "to suppose something is true without proof",
    "synonyms": ["presume","suppose","believe","take for granted"],
    "antonyms": ["know","prove","verify","confirm"],
    "example_sentence": "Do not ___ you know the answer without reading carefully.",
    "word_family": "assumption, assumptive",
    "collocations": "assume responsibility, assume control, safe to assume",
    "taboo_words": ["presume","suppose","believe","think","guess"]
  },
  {
    "sublist": 1,
    "word": "authority",
    "pos": "noun",
    "definition": "the power or right to make decisions",
    "synonyms": ["power","control","jurisdiction","command"],
    "antonyms": ["powerlessness","weakness","submission"],
    "example_sentence": "The school has the ___ to set its own rules.",
    "word_family": "authorise, authoritative, unauthorised",
    "collocations": "have authority over, authority figure, in authority",
    "taboo_words": ["power","control","command","right","permission"]
  },
  {
    "sublist": 1,
    "word": "available",
    "pos": "adjective",
    "definition": "able to be obtained or used",
    "synonyms": ["accessible","obtainable","free","at hand"],
    "antonyms": ["unavailable","restricted","inaccessible"],
    "example_sentence": "Clean drinking water is not always ___ in dry regions.",
    "word_family": "availability, unavailable",
    "collocations": "readily available, available to all, make available",
    "taboo_words": ["accessible","obtainable","free","open","on offer"]
  },
  {
    "sublist": 1,
    "word": "benefit",
    "pos": "noun / verb",
    "definition": "an advantage or helpful effect",
    "synonyms": ["advantage","gain","reward","asset"],
    "antonyms": ["disadvantage","harm","loss","drawback"],
    "example_sentence": "One ___ of reading widely is a stronger vocabulary.",
    "word_family": "beneficial, beneficiary, benefactor",
    "collocations": "benefit from, for the benefit of, mutual benefit",
    "taboo_words": ["advantage","gain","reward","profit","asset"]
  },
  {
    "sublist": 1,
    "word": "concept",
    "pos": "noun",
    "definition": "an idea or principle",
    "synonyms": ["idea","notion","principle","theory"],
    "antonyms": ["reality","fact","concrete thing"],
    "example_sentence": "Democracy is a ___ that values equal voting rights.",
    "word_family": "conceptual, conceptualise",
    "collocations": "basic concept, key concept, grasp a concept",
    "taboo_words": ["idea","notion","principle","theory","thought"]
  },
  {
    "sublist": 1,
    "word": "consist",
    "pos": "verb",
    "definition": "to be made up of particular parts or elements",
    "synonyms": ["comprise","include","contain","be composed of"],
    "antonyms": ["exclude","omit","lack"],
    "example_sentence": "A balanced diet should ___ of proteins, carbohydrates, and vitamins.",
    "word_family": "consistent, consistency, inconsistent",
    "collocations": "consist of, entirely consists of",
    "taboo_words": ["comprise","include","contain","be made up of","involve"]
  },
  {
    "sublist": 1,
    "word": "constitute",
    "pos": "verb",
    "definition": "to make up or form something",
    "synonyms": ["form","make up","compose","represent"],
    "antonyms": ["exclude","omit"],
    "example_sentence": "Young people ___ the majority of the country's population.",
    "word_family": "constitution, constitutional, constituent",
    "collocations": "constitute a majority, constitute a threat, legally constitute",
    "taboo_words": ["form","make up","compose","represent","account for"]
  },
  {
    "sublist": 1,
    "word": "context",
    "pos": "noun",
    "definition": "the circumstances surrounding something",
    "synonyms": ["background","setting","circumstances","situation"],
    "antonyms": ["isolation","vacuum"],
    "example_sentence": "You must read the ___ of a sentence to understand unfamiliar words.",
    "word_family": "contextual, contextualise, contextually",
    "collocations": "in context, out of context, historical context",
    "taboo_words": ["background","setting","situation","circumstances","environment"]
  },
  {
    "sublist": 1,
    "word": "contract",
    "pos": "noun / verb",
    "definition": "a formal agreement; or to decrease in size",
    "synonyms": ["agreement","deal","treaty / shrink","reduce","decrease"],
    "antonyms": ["disagreement / expand","grow","extend"],
    "example_sentence": "The athlete signed a ___ with the sports club.",
    "word_family": "contractor, contractual, subcontract",
    "collocations": "sign a contract, breach a contract, contract work",
    "taboo_words": ["agreement","deal","document","arrangement","treaty"]
  },
  {
    "sublist": 1,
    "word": "create",
    "pos": "verb",
    "definition": "to make or produce something new",
    "synonyms": ["make","produce","generate","design"],
    "antonyms": ["destroy","demolish","eliminate"],
    "example_sentence": "Artists ___ works that express human emotions.",
    "word_family": "creation, creative, creativity, creator",
    "collocations": "create an opportunity, create a problem, create awareness",
    "taboo_words": ["make","produce","generate","build","develop"]
  },
  {
    "sublist": 1,
    "word": "data",
    "pos": "noun",
    "definition": "facts and statistics collected for analysis",
    "synonyms": ["information","statistics","facts","figures"],
    "antonyms": ["opinion","speculation","guesswork"],
    "example_sentence": "Scientists collect ___ over many years before drawing conclusions.",
    "word_family": "database, data-driven",
    "collocations": "collect data, analyse data, data suggests, raw data",
    "taboo_words": ["information","statistics","facts","figures","evidence"]
  },
  {
    "sublist": 1,
    "word": "define",
    "pos": "verb",
    "definition": "to explain the meaning of something",
    "synonyms": ["explain","describe","clarify","specify"],
    "antonyms": ["confuse","obscure","complicate"],
    "example_sentence": "The dictionary will ___ the word for you.",
    "word_family": "definition, definite, indefinite, redefine",
    "collocations": "define a term, clearly define, hard to define",
    "taboo_words": ["explain","describe","clarify","specify","outline"]
  },
  {
    "sublist": 1,
    "word": "derive",
    "pos": "verb",
    "definition": "to obtain something from a source",
    "synonyms": ["obtain","gain","draw","get","extract"],
    "antonyms": ["give","provide","supply"],
    "example_sentence": "Many English words ___ from Latin roots.",
    "word_family": "derivative, derivation",
    "collocations": "derive benefit from, derive meaning, derive satisfaction",
    "taboo_words": ["obtain","get","draw","extract","take"]
  },
  {
    "sublist": 1,
    "word": "distribute",
    "pos": "verb",
    "definition": "to share or spread something among people",
    "synonyms": ["share","spread","hand out","allocate","dispense"],
    "antonyms": ["collect","gather","keep","centralise"],
    "example_sentence": "The charity will ___ food to families in need.",
    "word_family": "distribution, distributor, redistribution",
    "collocations": "distribute evenly, distribute resources, distribute power",
    "taboo_words": ["share","spread","hand out","give out","allocate"]
  },
  {
    "sublist": 1,
    "word": "economy",
    "pos": "noun",
    "definition": "the system of money and trade in a country",
    "synonyms": ["financial system","trade","commerce","market"],
    "antonyms": ["poverty","underdevelopment"],
    "example_sentence": "Tourism plays a vital role in the country's ___.",
    "word_family": "economic, economical, economist, economise",
    "collocations": "global economy, boost the economy, economy grows",
    "taboo_words": ["financial system","market","trade","commerce","industry"]
  },
  {
    "sublist": 1,
    "word": "environment",
    "pos": "noun",
    "definition": "the natural world, or the surroundings in which something exists",
    "synonyms": ["surroundings","habitat","nature","ecosystem"],
    "antonyms": ["built environment","artificial setting"],
    "example_sentence": "Plastic waste is one of the biggest threats to the ___.",
    "word_family": "environmental, environmentalist, environmentally",
    "collocations": "protect the environment, natural environment, work environment",
    "taboo_words": ["surroundings","habitat","nature","setting","ecosystem"]
  },
  {
    "sublist": 1,
    "word": "establish",
    "pos": "verb",
    "definition": "to set up or create something permanent",
    "synonyms": ["set up","found","create","institute","build"],
    "antonyms": ["abolish","destroy","dismantle","end"],
    "example_sentence": "The Red Cross was ___ to help people affected by war.",
    "word_family": "establishment, established, re-establish",
    "collocations": "establish a link, well-established, establish contact",
    "taboo_words": ["set up","found","create","build","start"]
  },
  {
    "sublist": 1,
    "word": "estimate",
    "pos": "verb / noun",
    "definition": "to calculate approximately",
    "synonyms": ["calculate","approximate","gauge","reckon"],
    "antonyms": ["measure exactly","determine precisely"],
    "example_sentence": "Scientists ___ the universe is 13.8 billion years old.",
    "word_family": "estimation, overestimate, underestimate",
    "collocations": "rough estimate, conservative estimate, estimate suggests",
    "taboo_words": ["calculate","approximate","guess","reckon","judge"]
  },
  {
    "sublist": 1,
    "word": "evident",
    "pos": "adjective",
    "definition": "clearly seen or understood",
    "synonyms": ["obvious","clear","apparent","plain"],
    "antonyms": ["hidden","unclear","obscure","concealed"],
    "example_sentence": "It was ___ from her smile that she had passed the exam.",
    "word_family": "evidently, evidence, self-evident",
    "collocations": "clearly evident, become evident, make evident",
    "taboo_words": ["obvious","clear","apparent","plain","visible"]
  },
  {
    "sublist": 1,
    "word": "export",
    "pos": "verb / noun",
    "definition": "to send goods to another country for sale",
    "synonyms": ["sell abroad","trade","ship","sell overseas"],
    "antonyms": ["import","bring in"],
    "example_sentence": "Brazil is famous for exporting coffee around the world.",
    "word_family": "exporter, exportable, re-export",
    "collocations": "major export, export market, export goods",
    "taboo_words": ["sell abroad","trade","ship","send","sell overseas"]
  },
  {
    "sublist": 1,
    "word": "factor",
    "pos": "noun",
    "definition": "something that contributes to a result",
    "synonyms": ["element","aspect","cause","component"],
    "antonyms": ["result","effect","consequence","outcome"],
    "example_sentence": "Exercise is an important ___ in maintaining good health.",
    "word_family": "factorial",
    "collocations": "key factor, contributing factor, risk factor",
    "taboo_words": ["element","aspect","cause","component","part"]
  },
  {
    "sublist": 1,
    "word": "finance",
    "pos": "verb / noun",
    "definition": "to provide money for something; or the management of money",
    "synonyms": ["fund","support","back / money","economics","funding"],
    "antonyms": ["defund","withdraw"],
    "example_sentence": "The government agreed to ___ the new hospital.",
    "word_family": "financial, financially, financier",
    "collocations": "public finance, finance a project, minister of finance",
    "taboo_words": ["fund","pay for","support","back","sponsor"]
  },
  {
    "sublist": 1,
    "word": "formula",
    "pos": "noun",
    "definition": "a rule or method expressed in symbols or words",
    "synonyms": ["rule","equation","method","procedure"],
    "antonyms": ["guess","approximation","instinct"],
    "example_sentence": "There is no magic ___ for success in exams.",
    "word_family": "formulaic, formulate, formulation",
    "collocations": "mathematical formula, chemical formula, winning formula",
    "taboo_words": ["rule","equation","method","procedure","recipe"]
  },
  {
    "sublist": 1,
    "word": "function",
    "pos": "noun / verb",
    "definition": "the purpose or role of something",
    "synonyms": ["purpose","role","job","use","task"],
    "antonyms": ["malfunction","failure","dysfunction"],
    "example_sentence": "The main ___ of the heart is to pump blood.",
    "word_family": "functional, dysfunction, multifunctional",
    "collocations": "serve a function, main function, function properly",
    "taboo_words": ["purpose","role","job","use","task"]
  },
  {
    "sublist": 1,
    "word": "identify",
    "pos": "verb",
    "definition": "to recognise or find out who or what something is",
    "synonyms": ["recognise","spot","determine","detect","pinpoint"],
    "antonyms": ["ignore","miss","overlook","fail to notice"],
    "example_sentence": "Police used CCTV to ___ the suspect.",
    "word_family": "identification, identity, identifiable",
    "collocations": "identify a problem, identify with, clearly identified",
    "taboo_words": ["recognise","spot","determine","detect","find"]
  },
  {
    "sublist": 1,
    "word": "income",
    "pos": "noun",
    "definition": "money received regularly for work or investment",
    "synonyms": ["earnings","wages","salary","revenue","pay"],
    "antonyms": ["expenditure","spending","outgoings","loss"],
    "example_sentence": "A higher ___ usually means a better standard of living.",
    "word_family": "low-income, high-income",
    "collocations": "household income, income tax, disposable income",
    "taboo_words": ["earnings","wages","salary","pay","revenue"]
  },
  {
    "sublist": 1,
    "word": "indicate",
    "pos": "verb",
    "definition": "to show or suggest something",
    "synonyms": ["show","suggest","signal","point to","imply"],
    "antonyms": ["hide","conceal","mislead","obscure"],
    "example_sentence": "Rising sea levels ___ that climate change is accelerating.",
    "word_family": "indication, indicator, indicative",
    "collocations": "results indicate, clearly indicate, indicate a trend",
    "taboo_words": ["show","suggest","signal","point to","demonstrate"]
  },
  {
    "sublist": 1,
    "word": "individual",
    "pos": "noun / adjective",
    "definition": "a single person, or relating to one person",
    "synonyms": ["person","human being / single","personal","particular"],
    "antonyms": ["group","collective","communal"],
    "example_sentence": "Every ___ has the right to a fair trial.",
    "word_family": "individually, individualism, individualist",
    "collocations": "every individual, individual needs, individual rights",
    "taboo_words": ["person","human","single","particular","specific"]
  },
  {
    "sublist": 1,
    "word": "interpret",
    "pos": "verb",
    "definition": "to explain or understand the meaning of something",
    "synonyms": ["explain","understand","translate","read","construe"],
    "antonyms": ["misunderstand","confuse","misinterpret"],
    "example_sentence": "Different people may ___ the same poem in different ways.",
    "word_family": "interpretation, interpreter, misinterpret",
    "collocations": "interpret results, open to interpretation, interpret data",
    "taboo_words": ["explain","understand","translate","read","construe"]
  },
  {
    "sublist": 1,
    "word": "involve",
    "pos": "verb",
    "definition": "to include or affect someone or something",
    "synonyms": ["include","affect","require","encompass","entail"],
    "antonyms": ["exclude","omit","leave out"],
    "example_sentence": "The project will ___ students from all year groups.",
    "word_family": "involvement, involved, uninvolved",
    "collocations": "involve risk, actively involved, involve the community",
    "taboo_words": ["include","affect","require","need","entail"]
  },
  {
    "sublist": 1,
    "word": "issue",
    "pos": "noun",
    "definition": "an important topic or problem",
    "synonyms": ["topic","matter","problem","concern","question"],
    "antonyms": ["solution","answer","resolution"],
    "example_sentence": "Climate change is the most urgent ___ of our time.",
    "word_family": "issues",
    "collocations": "key issue, raise an issue, address an issue",
    "taboo_words": ["topic","matter","problem","concern","question"]
  },
  {
    "sublist": 1,
    "word": "labour",
    "pos": "noun",
    "definition": "work, especially physical work",
    "synonyms": ["work","effort","toil","workforce","workers"],
    "antonyms": ["rest","leisure","idleness","relaxation"],
    "example_sentence": "Building the pyramids required the ___ of thousands of workers.",
    "word_family": "labourer, laborious, labour-intensive",
    "collocations": "hard labour, labour market, division of labour",
    "taboo_words": ["work","effort","toil","workforce","manpower"]
  },
  {
    "sublist": 1,
    "word": "legal",
    "pos": "adjective",
    "definition": "allowed by or connected to the law",
    "synonyms": ["lawful","permitted","valid","legitimate"],
    "antonyms": ["illegal","unlawful","forbidden","prohibited"],
    "example_sentence": "It is not ___ to drive without a valid licence.",
    "word_family": "legally, legalise, illegal, legality",
    "collocations": "legal advice, legal action, legal system",
    "taboo_words": ["lawful","legitimate","permitted","valid","official"]
  },
  {
    "sublist": 1,
    "word": "legislate",
    "pos": "verb",
    "definition": "to make laws",
    "synonyms": ["make laws","pass laws","enact","decree"],
    "antonyms": ["repeal","abolish","overturn"],
    "example_sentence": "Parliament will ___ to protect workers from unfair dismissal.",
    "word_family": "legislation, legislative, legislator",
    "collocations": "legislate against, legislate for, power to legislate",
    "taboo_words": ["pass laws","make laws","enact","decree","regulate"]
  },
  {
    "sublist": 1,
    "word": "major",
    "pos": "adjective",
    "definition": "important, serious, or large in scale",
    "synonyms": ["important","significant","serious","key","main"],
    "antonyms": ["minor","trivial","small","insignificant"],
    "example_sentence": "The discovery of penicillin was a ___ breakthrough in medicine.",
    "word_family": "majority, majorly",
    "collocations": "major issue, major role, play a major part",
    "taboo_words": ["important","significant","serious","key","main"]
  },
  {
    "sublist": 1,
    "word": "method",
    "pos": "noun",
    "definition": "a particular way of doing something",
    "synonyms": ["way","approach","technique","procedure","system"],
    "antonyms": ["disorder","randomness","chaos"],
    "example_sentence": "The experimental ___ involves testing ideas through observation.",
    "word_family": "methodical, methodology, methodically",
    "collocations": "research method, teaching method, by this method",
    "taboo_words": ["way","approach","technique","procedure","system"]
  },
  {
    "sublist": 1,
    "word": "occur",
    "pos": "verb",
    "definition": "to happen or take place",
    "synonyms": ["happen","take place","arise","come about","emerge"],
    "antonyms": ["prevent","avoid","stop"],
    "example_sentence": "Earthquakes ___ when tectonic plates shift suddenly.",
    "word_family": "occurrence, reoccur",
    "collocations": "frequently occurs, occur naturally, when this occurs",
    "taboo_words": ["happen","take place","arise","come about","appear"]
  },
  {
    "sublist": 1,
    "word": "percent",
    "pos": "noun",
    "definition": "a proportion expressed as a fraction of 100",
    "synonyms": ["proportion","fraction","share","ratio"],
    "antonyms": ["whole","total"],
    "example_sentence": "About 70 ___ of the Earth's surface is covered by water.",
    "word_family": "percentage, percentile",
    "collocations": "20 percent, percent increase, what percent",
    "taboo_words": ["proportion","fraction","share","portion","ratio"]
  },
  {
    "sublist": 1,
    "word": "period",
    "pos": "noun",
    "definition": "a length or stretch of time",
    "synonyms": ["time","phase","era","stage","span"],
    "antonyms": ["moment","instant","point in time"],
    "example_sentence": "The Ice Age was a ___ of extreme cold lasting thousands of years.",
    "word_family": "periodic, periodically",
    "collocations": "period of time, over a period, historical period",
    "taboo_words": ["time","phase","era","stage","spell"]
  },
  {
    "sublist": 1,
    "word": "policy",
    "pos": "noun",
    "definition": "a set of rules or a plan of action",
    "synonyms": ["rules","guidelines","plan","strategy","approach"],
    "antonyms": ["disorder","flexibility","absence of rules"],
    "example_sentence": "The school has a strict ___ on the use of mobile phones.",
    "word_family": "policymaker",
    "collocations": "government policy, policy change, foreign policy",
    "taboo_words": ["rules","guidelines","plan","strategy","approach"]
  },
  {
    "sublist": 1,
    "word": "principle",
    "pos": "noun",
    "definition": "a basic rule or belief that guides behaviour",
    "synonyms": ["rule","belief","value","tenet","standard"],
    "antonyms": ["exception","flexibility","rule-breaking"],
    "example_sentence": "The ___ of fairness means everyone should be treated equally.",
    "word_family": "principled, unprincipled",
    "collocations": "on principle, guiding principle, in principle",
    "taboo_words": ["rule","belief","value","standard","tenet"]
  },
  {
    "sublist": 1,
    "word": "proceed",
    "pos": "verb",
    "definition": "to continue or go forward with something",
    "synonyms": ["continue","go ahead","advance","carry on","press on"],
    "antonyms": ["stop","halt","retreat","abandon"],
    "example_sentence": "The builders were given permission to ___ with construction.",
    "word_family": "proceedings, procedure, proceeds",
    "collocations": "proceed with caution, how to proceed, proceed as planned",
    "taboo_words": ["continue","go ahead","carry on","advance","press on"]
  },
  {
    "sublist": 1,
    "word": "process",
    "pos": "noun / verb",
    "definition": "a series of actions to achieve a result",
    "synonyms": ["procedure","method","system","sequence","operation"],
    "antonyms": ["disorder","chaos","randomness"],
    "example_sentence": "Photosynthesis is the ___ by which plants make food from sunlight.",
    "word_family": "processor, processed, processing",
    "collocations": "in the process of, complex process, decision-making process",
    "taboo_words": ["procedure","method","system","sequence","operation"]
  },
  {
    "sublist": 1,
    "word": "require",
    "pos": "verb",
    "definition": "to need something, or to make something necessary",
    "synonyms": ["need","demand","necessitate","call for","depend on"],
    "antonyms": ["provide","supply","offer","give"],
    "example_sentence": "This exercise will ___ concentration and careful reading.",
    "word_family": "requirement, required, prerequisite",
    "collocations": "require attention, as required, minimum requirement",
    "taboo_words": ["need","demand","call for","necessitate","depend on"]
  },
  {
    "sublist": 1,
    "word": "research",
    "pos": "noun / verb",
    "definition": "careful study to discover new facts",
    "synonyms": ["study","investigation","inquiry","analysis","exploration"],
    "antonyms": ["assumption","guesswork","speculation"],
    "example_sentence": "Scientists carry out ___ for many years before publishing results.",
    "word_family": "researcher, research-based",
    "collocations": "carry out research, research suggests, research into",
    "taboo_words": ["study","investigation","inquiry","analysis","examination"]
  },
  {
    "sublist": 1,
    "word": "respond",
    "pos": "verb",
    "definition": "to say or do something in reply or reaction",
    "synonyms": ["reply","react","answer","counter","react to"],
    "antonyms": ["ignore","stay silent","fail to respond"],
    "example_sentence": "The government was slow to ___ to the flooding disaster.",
    "word_family": "response, responsive, respondent",
    "collocations": "respond to a question, respond positively, fail to respond",
    "taboo_words": ["reply","react","answer","counter","address"]
  },
  {
    "sublist": 1,
    "word": "role",
    "pos": "noun",
    "definition": "the function or position of a person or thing",
    "synonyms": ["function","part","position","responsibility","duty"],
    "antonyms": ["insignificance","irrelevance"],
    "example_sentence": "Teachers play a vital ___ in a child's development.",
    "word_family": "role model, role-play",
    "collocations": "play a role, key role, take on a role",
    "taboo_words": ["function","part","position","responsibility","job"]
  },
  {
    "sublist": 1,
    "word": "section",
    "pos": "noun",
    "definition": "a distinct part of something larger",
    "synonyms": ["part","portion","segment","division","component"],
    "antonyms": ["whole","entirety","totality"],
    "example_sentence": "The final ___ of the paper tests reading comprehension.",
    "word_family": "sectional, cross-section",
    "collocations": "in this section, cross-section, section of society",
    "taboo_words": ["part","portion","segment","division","piece"]
  },
  {
    "sublist": 1,
    "word": "sector",
    "pos": "noun",
    "definition": "a distinct part of the economy or society",
    "synonyms": ["part","area","division","field","branch"],
    "antonyms": ["whole","entirety"],
    "example_sentence": "The technology ___ has grown rapidly in recent decades.",
    "word_family": "sectoral",
    "collocations": "private sector, public sector, sector of the economy",
    "taboo_words": ["part","area","division","field","branch"]
  },
  {
    "sublist": 1,
    "word": "significant",
    "pos": "adjective",
    "definition": "important or large enough to be noticed",
    "synonyms": ["important","notable","considerable","substantial","meaningful"],
    "antonyms": ["insignificant","trivial","minor","negligible"],
    "example_sentence": "There has been a ___ increase in students studying science.",
    "word_family": "significantly, significance, insignificant",
    "collocations": "statistically significant, highly significant, significant change",
    "taboo_words": ["important","notable","considerable","meaningful","substantial"]
  },
  {
    "sublist": 1,
    "word": "similar",
    "pos": "adjective",
    "definition": "almost the same but not identical",
    "synonyms": ["alike","comparable","close","related","parallel"],
    "antonyms": ["different","unlike","contrasting","dissimilar"],
    "example_sentence": "The two experiments produced ___ results.",
    "word_family": "similarly, similarity, dissimilar",
    "collocations": "similar to, in a similar way, broadly similar",
    "taboo_words": ["alike","comparable","close","equivalent","related"]
  },
  {
    "sublist": 1,
    "word": "source",
    "pos": "noun",
    "definition": "the place or thing from which something comes",
    "synonyms": ["origin","cause","root","supply","basis"],
    "antonyms": ["result","effect","outcome","product"],
    "example_sentence": "The sun is the main ___ of energy for life on Earth.",
    "word_family": "sourced",
    "collocations": "primary source, source of income, cite your sources",
    "taboo_words": ["origin","cause","root","supply","origin"]
  },
  {
    "sublist": 1,
    "word": "specific",
    "pos": "adjective",
    "definition": "clearly defined or identified",
    "synonyms": ["particular","precise","exact","definite","explicit"],
    "antonyms": ["general","vague","broad","unspecified"],
    "example_sentence": "The instructions were very ___ about how to complete the task.",
    "word_family": "specifically, specification, specify",
    "collocations": "be specific, specific example, specific to",
    "taboo_words": ["particular","precise","exact","definite","clear"]
  },
  {
    "sublist": 1,
    "word": "structure",
    "pos": "noun",
    "definition": "the way something is organised or built",
    "synonyms": ["organisation","framework","form","arrangement","system"],
    "antonyms": ["chaos","disorder","randomness","disorganisation"],
    "example_sentence": "The ___ of a good essay includes an introduction and conclusion.",
    "word_family": "structural, structurally, restructure, unstructured",
    "collocations": "organisational structure, sentence structure, underlying structure",
    "taboo_words": ["organisation","framework","form","arrangement","system"]
  },
  {
    "sublist": 1,
    "word": "theory",
    "pos": "noun",
    "definition": "an explanation based on evidence and reasoning",
    "synonyms": ["explanation","hypothesis","idea","model","framework"],
    "antonyms": ["fact","proof","certainty","established truth"],
    "example_sentence": "Darwin's ___ of evolution changed how we understand life on Earth.",
    "word_family": "theoretical, theorist, theorise",
    "collocations": "in theory, support a theory, theoretical framework",
    "taboo_words": ["explanation","hypothesis","idea","model","concept"]
  },
  {
    "sublist": 1,
    "word": "vary",
    "pos": "verb",
    "definition": "to be different, or to change",
    "synonyms": ["differ","change","fluctuate","alternate","shift"],
    "antonyms": ["stay the same","remain constant","be uniform"],
    "example_sentence": "Temperatures ___ greatly between summer and winter.",
    "word_family": "variation, variable, variety, varied, various",
    "collocations": "vary widely, vary considerably, prices vary",
    "taboo_words": ["differ","change","fluctuate","shift","alternate"]
  },

  // ── SUBLIST 2 ──────────────────────────────────────────────────────
  {"sublist":2,"word":"achieve","pos":"verb","definition":"to successfully reach an objective or result by effort or skill","synonyms":["accomplish","attain","reach","fulfill"],"antonyms":["fail","abandon","miss"],"example_sentence":"He worked hard to ___ his ambition of becoming an engineer.","word_family":"achievable, achievement, achiever","collocations":"achieve a goal, achieve success, achieve results","taboo_words":["accomplish","attain","reach","goal","success"]},
  {"sublist":2,"word":"acquire","pos":"verb","definition":"to buy or obtain an asset, object, or skill","synonyms":["obtain","gain","buy","procure"],"antonyms":["lose","surrender","forfeit"],"example_sentence":"The company plans to ___ its main competitor next year.","word_family":"acquisition, acquired, acquisitive","collocations":"acquire a skill, acquire language, newly acquired","taboo_words":["obtain","get","gain","buy","asset"]},
  {"sublist":2,"word":"administrate","pos":"verb","definition":"to manage and organize the operation of a business or institution","synonyms":["manage","direct","govern","supervise"],"antonyms":["subordinate","follow","mismanage"],"example_sentence":"The department was set up to ___ the new student fund.","word_family":"administration, administrative, administrator","collocations":"administrate a program, administrative staff, day-to-day administration","taboo_words":["manage","run","office","executive","boss"]},
  {"sublist":2,"word":"affect","pos":"verb","definition":"to have an influence on or make a difference to something","synonyms":["influence","impact","alter","modify"],"antonyms":["remain","stagnate"],"example_sentence":"The cold weather will directly ___ the crop yields this season.","word_family":"effect, affected, affecting, unaffected","collocations":"adversely affect, directly affect, affect the outcome","taboo_words":["influence","change","impact","effect","alter"]},
  {"sublist":2,"word":"appropriate","pos":"adjective","definition":"suitable or proper in the circumstances","synonyms":["suitable","proper","fitting","apt"],"antonyms":["inappropriate","unsuitable","improper"],"example_sentence":"Please ensure you wear ___ clothing to the formal dinner.","word_family":"appropriately, appropriateness, inappropriacy","collocations":"appropriate behavior, highly appropriate, deem appropriate","taboo_words":["suitable","proper","right","fit","correct"]},
  {"sublist":2,"word":"aspect","pos":"noun","definition":"a particular part, feature, or feature of something","synonyms":["feature","part","side","facet"],"antonyms":["whole","totality"],"example_sentence":"Every ___ of the plan was analyzed by the committee.","word_family":"aspects","collocations":"key aspect, every aspect, positive aspect","taboo_words":["part","feature","side","facet","element"]},
  {"sublist":2,"word":"assist","pos":"verb","definition":"to give help or support to someone in a task","synonyms":["help","aid","support","back"],"antonyms":["hinder","obstruct","impede"],"example_sentence":"A nurse was called to ___ the doctor with the surgery.","word_family":"assistance, assistant, assisted, unassisted","collocations":"assist with, ready to assist, assist in development","taboo_words":["help","aid","support","hand","assistant"]},
  {"sublist":2,"word":"category","pos":"noun","definition":"a class or division of people or things regarded as having shared characteristics","synonyms":["group","class","type","kind"],"antonyms":["entity","whole"],"example_sentence":"The data fell into a distinct ___ that researchers hadn't expected.","word_family":"categorize, categorization, categorical","collocations":"broad category, fall into a category, distinct category","taboo_words":["group","class","type","kind","sort"]},
  {"sublist":2,"word":"community","pos":"noun","definition":"a group of people living in the same place or sharing a common characteristic","synonyms":["society","neighborhood","population","public"],"antonyms":["individual","isolation"],"example_sentence":"The local ___ rallied together to build a new playground.","word_family":"communal, communities","collocations":"local community, sense of community, community service","taboo_words":["people","group","society","local","town"]},
  {"sublist":2,"word":"complex","pos":"adjective","definition":"consisting of many different and connected parts; difficult to understand","synonyms":["complicated","intricate","detailed","elaborate"],"antonyms":["simple","straightforward","basic"],"example_sentence":"The human brain is a ___ network of billions of neurons.","word_family":"complexity, complexly, complexities","collocations":"complex system, highly complex, complex issue","taboo_words":["hard","difficult","complicated","intricate","simple"]},
  {"sublist":2,"word":"conclude","pos":"verb","definition":"to bring something to an end, or to arrive at a judgment by reasoning","synonyms":["finish","end","deduce","infer"],"antonyms":["start","begin","initiate"],"example_sentence":"The report will ___ with a list of practical recommendations.","word_family":"conclusion, conclusive, conclusively, inconclusive","collocations":"conclude a speech, lead to conclude, safely conclude","taboo_words":["end","finish","decide","close","stop"]},
  {"sublist":2,"word":"conduct","pos":"verb / noun","definition":"to organize and carry out an activity; or a person's behavior","synonyms":["carry out","run","behavior","actions"],"antonyms":["neglect","misconduct"],"example_sentence":"The university will ___ a survey on student mental health.","word_family":"conductor, conducted, conducting","collocations":"conduct research, conduct an experiment, professional conduct","taboo_words":["behavior","run","do","lead","manage"]},
  {"sublist":2,"word":"construct","pos":"verb","definition":"to build or erect something large, such as a building or road","synonyms":["build","erect","assemble","create"],"antonyms":["demolish","destroy","dismantle"],"example_sentence":"They plan to ___ a new office block in the city center.","word_family":"construction, constructive, structural","collocations":"construct a building, structurally construct, construct an argument","taboo_words":["build","make","create","structure","erect"]},
  {"sublist":2,"word":"consume","pos":"verb","definition":"to eat, drink, or use up resources completely","synonyms":["use up","devour","exhaust","spend"],"antonyms":["produce","save","preserve"],"example_sentence":"Industrial machines ___ vast amounts of electricity every day.","word_family":"consumer, consumption, consuming","collocations":"consume energy, consume food, time-consuming","taboo_words":["eat","drink","use","spend","food"]},
  {"sublist":2,"word":"credit","pos":"noun / verb","definition":"an arrangement to receive cash or goods now and pay later; or acknowledgement","synonyms":["trust","recognition","financing","praise"],"antonyms":["blame","cash payment","discredit"],"example_sentence":"The bank extended their ___ limit to help with business expenses.","word_family":"creditor, creditable, credits","collocations":"credit limit, give credit to, credit history","taboo_words":["money","trust","loan","score","buy"]},
  {"sublist":2,"word":"culture","pos":"noun","definition":"the shared ideas, customs, and social behavior of a particular society","synonyms":["society","traditions","customs","heritage"],"antonyms":["nature","barbarism"],"example_sentence":"Studying ancient literature helps us understand the ___ of that era.","word_family":"cultural, culturally, cultured, cultures","collocations":"popular culture, corporate culture, cultural heritage","taboo_words":["society","traditions","customs","values","people"]},
  {"sublist":2,"word":"design","pos":"noun / verb","definition":"a plan or drawing produced to show the look and function of something before it is built","synonyms":["plan","blueprint","layout","sketch"],"antonyms":["randomness","chaos"],"example_sentence":"The architect unveiled the new ___ for the library expansion.","word_family":"designer, designing, designed","collocations":"interior design, design flaw, experimental design","taboo_words":["plan","draw","create","layout","art"]},
  {"sublist":2,"word":"evaluate","pos":"verb","definition":"to form an idea of the amount, number, or value of something","synonyms":["assess","appraise","rate","weigh"],"antonyms":["ignore","neglect"],"example_sentence":"The panel met to ___ the performance of each applicant.","word_family":"evaluation, evaluative, re-evaluate","collocations":"evaluate performance, carefully evaluate, evaluate options","taboo_words":["assess","judge","rate","score","measure"]},
  {"sublist":2,"word":"invest","pos":"verb","definition":"to put money or resources into something with the expectation of a profit or result","synonyms":["spend","venture","fund","back"],"antonyms":["divest","withdraw","spend foolishly"],"example_sentence":"They decided to ___ a massive portion of capital into tech updates.","word_family":"investment, investor, reinvest","collocations":"invest money, invest in stocks, heavily invest","taboo_words":["money","spend","buy","shares","stocks"]},
  {"sublist":2,"word":"obtain","pos":"verb","definition":"to come into possession of something; to get through effort","synonyms":["get","acquire","secure","gain"],"antonyms":["lose","forfeit","give up"],"example_sentence":"You must ___ written permission before entering the laboratory.","word_family":"obtainable, unobtainable, obtained","collocations":"obtain permission, obtain results, difficult to obtain","taboo_words":["get","gain","acquire","receive","take"]},

  // ── SUBLIST 3 ──────────────────────────────────────────────────────
  {"sublist":3,"word":"alternative","pos":"noun / adjective","definition":"one of two or more available possibilities or choices","synonyms":["option","choice","substitute","backup"],"antonyms":["compulsory","sole","mandatory"],"example_sentence":"If the flight is cancelled, our only ___ is to take the train.","word_family":"alternatively, alternatives","collocations":"alternative route, viable alternative, offer an alternative","taboo_words":["choice","option","substitute","other","different"]},
  {"sublist":3,"word":"circumstance","pos":"noun","definition":"a fact or condition connected with or relevant to an event or action","synonyms":["situation","condition","state","context"],"antonyms":["certainty","plan"],"example_sentence":"Due to an unforeseen ___, the meeting has been postponed indefinitely.","word_family":"circumstantial, circumstances","collocations":"under no circumstances, exceptional circumstances, economic circumstances","taboo_words":["situation","fact","condition","event","happen"]},
  {"sublist":3,"word":"comment","pos":"noun / verb","definition":"a statement expressing a personal opinion or reaction","synonyms":["remark","observation","statement","say"],"antonyms":["silence","ignore"],"example_sentence":"The minister refused to ___ on the ongoing investigation.","word_family":"commentary, commentator, commenting","collocations":"no comment, comment on, written comment","taboo_words":["say","remark","talk","opinion","mention"]},
  {"sublist":3,"word":"compensate","pos":"verb","definition":"to give someone something, typically money, in recognition of loss, suffering, or injury","synonyms":["reimburse","make up","offset","repay"],"antonyms":["penalize","deprive","take away"],"example_sentence":"The airline will ___ all passengers for the extreme delay.","word_family":"compensation, compensatory, compensates","collocations":"compensate for loss, financially compensate, compensate victims","taboo_words":["pay","money","make up","offset","loss"]},
  {"sublist":3,"word":"component","pos":"noun","definition":"a part or element of a larger whole, especially of a machine or system","synonyms":["part","piece","element","constituent"],"antonyms":["whole","entirety","aggregate"],"example_sentence":"Engineers checked every structural ___ before the rocket launch.","word_family":"components","collocations":"key component, major component, structural component","taboo_words":["part","piece","element","unit","member"]},
  {"sublist":3,"word":"consent","pos":"noun / verb","definition":"permission for something to happen or agreement to do something","synonyms":["agreement","permission","approval","assent"],"antonyms":["refusal","disagreement","dissent"],"example_sentence":"Medical procedures cannot go ahead without patient ___.","word_family":"consenting, consensus, consensual","collocations":"informed consent, parental consent, mutual consent","taboo_words":["agree","permission","yes","allow","approval"]},
  {"sublist":3,"word":"considerable","pos":"adjective","definition":"notably large in size, amount, extent, or importance","synonyms":["substantial","significant","sizeable","large"],"antonyms":["insignificant","minor","negligible","small"],"example_sentence":"The renovation project took a ___ amount of time and effort.","word_family":"considerably","collocations":"considerable amount, considerable progress, considerable influence","taboo_words":["large","big","much","significant","great"]},
  {"sublist":3,"word":"constant","pos":"adjective","definition":"occurring continuously over a period of time; remaining the same","synonyms":["continuous","steady","unchanging","perpetual"],"antonyms":["variable","irregular","intermittent"],"example_sentence":"The patient required ___ monitoring throughout the evening.","word_family":"constantly, constancy, constants","collocations":"constant stream, remain constant, constant reminder","taboo_words":["always","same","continuous","steady","change"]},
  {"sublist":3,"word":"constrain","pos":"verb","definition":"to severely restrict the scope, activity, or freedom of action of something","synonyms":["limit","restrict","bind","confine"],"antonyms":["free","liberate","release"],"example_sentence":"High inflation rates can heavily ___ economic expansion.","word_family":"constraint, constraints, constrained","collocations":"severely constrain, feel constrained, naturally constrain","taboo_words":["limit","restrict","hold","stop","bound"]},
  {"sublist":3,"word":"contribute","pos":"verb","definition":"to give something, especially money or support, to help achieve a joint result","synonyms":["donate","give","provide","add"],"antonyms":["withhold","take","withdraw"],"example_sentence":"Every employee was asked to ___ ideas toward the restructuring strategy.","word_family":"contribution, contributor, contributory","collocations":"contribute to, significantly contribute, contribute funds","taboo_words":["give","share","add","help","donation"]},
  {"sublist":3,"word":"core","pos":"noun / adjective","definition":"the central, most essential, or foundational part of something","synonyms":["center","heart","foundation","basis"],"antonyms":["periphery","surface","exterior"],"example_sentence":"Honesty is one of the ___ values of our school community.","word_family":"cores","collocations":"core values, core business, core subject","taboo_words":["center","main","middle","heart","base"]},
  {"sublist":3,"word":"corporate","pos":"adjective","definition":"relating to a large company or business group","synonyms":["business","commercial","company","enterprise"],"antonyms":["individual","private","personal"],"example_sentence":"She climbed the ___ ladder to become a managing director.","word_family":"corporation, corporate","collocations":"corporate strategy, corporate image, corporate governance","taboo_words":["company","business","firm","office","commercial"]},
  {"sublist":3,"word":"criteria","pos":"noun","definition":"principles or standards by which something may be judged or decided","synonyms":["standards","benchmarks","measures","requirements"],"antonyms":["fancy","guesswork"],"example_sentence":"The selection ___ for the global grant program are incredibly strict.","word_family":"criterion","collocations":"meet the criteria, strict criteria, evaluation criteria","taboo_words":["rules","standards","requirements","judge","basis"]},
  {"sublist":3,"word":"demonstrate","pos":"verb","definition":"to clearly show the existence or truth of something by giving proof or evidence","synonyms":["show","prove","display","manifest"],"antonyms":["hide","disprove","conceal"],"example_sentence":"The experiment was designed to ___ how pressure alters chemical structure.","word_family":"demonstration, demonstrative, demonstrable","collocations":"clearly demonstrate, demonstrate a need, demonstrate competence","taboo_words":["show","prove","display","evidence","explain"]},
  {"sublist":3,"word":"document","pos":"noun / verb","definition":"a piece of written, printed, or electronic matter that provides information; or to record details","synonyms":["paper","record","file","log"],"antonyms":["erase","obliterate"],"example_sentence":"Please sign the official legal ___ before returning it to the office.","word_family":"documentation, documented, documenting","collocations":"legal document, document details, official documentation","taboo_words":["paper","file","record","write","text"]},
  {"sublist":3,"word":"dominate","pos":"verb","definition":"to have a commanding influence or exercise control over something or someone","synonyms":["control","rule","overshadow","monopolize"],"antonyms":["submit","follow","yield"],"example_sentence":"Tech companies continue to ___ the modern stock market indexes.","word_family":"dominant, dominance, domination","collocations":"dominate the market, dominate conversation, completely dominate","taboo_words":["control","rule","lead","power","boss"]},
  {"sublist":3,"word":"emphasis","pos":"noun","definition":"special importance, value, or prominence given to something","synonyms":["stress","weight","priority","importance"],"antonyms":["neglect","insignificance"],"example_sentence":"The school curriculum puts high ___ on digital tech literacy.","word_family":"emphasize, emphatic, emphatically","collocations":"place emphasis on, shift the emphasis, primary emphasis","taboo_words":["stress","focus","importance","highlight","mark"]},
  {"sublist":3,"word":"ensure","pos":"verb","definition":"to make certain that something will occur or be the case","synonyms":["guarantee","make sure","secure","confirm"],"antonyms":["endanger","neglect","risk"],"example_sentence":"Double-check the data rows to ___ full accuracy before loading.","word_family":"ensured, ensuring, ensures","collocations":"ensure safety, ensure compliance, steps to ensure","taboo_words":["make sure","guarantee","certain","secure","check"]},
  {"sublist":3,"word":"framework","pos":"noun","definition":"an underlying supporting structure or system for a larger concept","synonyms":["structure","system","skeleton","architecture"],"antonyms":["chaos","disorganization"],"example_sentence":"The policy operates inside a strict regulatory ___ set by parliament.","word_family":"frameworks","collocations":"conceptual framework, regulatory framework, structural framework","taboo_words":["structure","system","support","base","skeleton"]},
  {"sublist":3,"word":"fund","pos":"noun / verb","definition":"a sum of money saved or made available for a particular purpose; or to provide money","synonyms":["finance","sponsor","capital","endowment"],"antonyms":["defund","spend"],"example_sentence":"The government agreed to ___ the entire infrastructure operation.","word_family":"funding, funded, funder","collocations":"public fund, fund a project, investment fund","taboo_words":["money","pay","finance","cash","grant"]},
  {"sublist":3,"word":"technology","pos":"noun","definition":"the practical application of scientific knowledge for industrial or commercial purposes","synonyms":["machinery","computing","digital systems","electronics"],"antonyms":["nature","antiquity"],"example_sentence":"Rapid shifts in computer ___ change how database architectures function.","word_family":"technological, technologically, technologist","collocations":"modern technology, information technology, communications technology","taboo_words":["science","computer","machine","digital","tool"]}
];
